
---
## PersistentVolumeClaim

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${envfileName}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi


---
## pod

apiVersion: v1
kind: Pod
metadata:
  name: ${pvcContainer}-pod
spec:
  containers:
    - name: pvc-${envfileName}-container
      image: us.gcr.io/tg-tool/k8small:latest
      resources:
        limits:
          cpu: 40m
      volumeMounts:
        - name: ${envfileName}-volume
          mountPath: /app/${envfileName}
      # readinessProbe:
      #  exec:
      #    command:
      #    - cat
      #    - /tmp/healthy
      #  initialDelaySeconds: 5
      #  periodSeconds: 30
  volumes:
    - name: ${envfileName}-volume
      persistentVolumeClaim:
        claimName: ${envfileName}

